service: tmunan-orc

provider:
  name: aws
  stage: prod
  runtime: python3.11
  region: eu-west-1
  environment:
    ECS_CLUSTER_NAME: tmunan_cluster
    TASK_DEFINITION: tmunan_task
    CONTAINER_NAME: stream
  iam:
    role: arn:aws:iam::090268630745:role/github_deploy_role
  deploymentBucket:
    name: tmunan-deployment-bucket
    serverSideEncryption: AES256  # Optional: Enables server-side encryption

package:
  individually: true
  exclude:
    - ".*/**"

functions:
  runSession:
    handler: orc.run_session.handler.run_session
    role: arn:aws:iam::090268630745:role/tmunan_orc_execution_role
    package:
      include:
        - orc/**
    events:
      - http:
          path: run_session
          method: post

#plugins:
#  - serverless-python-requirements
