version: "3"

services:
  app:
    restart: unless-stopped
    image: ${APP_IMAGE_NAME}
    ports:
      - "8080:8080"
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "100k"

  nginx:
      restart: unless-stopped
      image: nginx
      container_name: nginx
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ${NGINX_CONF}:/etc/nginx/conf.d/default.conf:ro
        - /etc/letsencrypt:/etc/letsencrypt
      depends_on:
        - app
      logging:
        driver: "json-file"
        options:
          max-size: "100k"
          max-file: "1"
