name: Deploy Tmunan Orchestration

on:
  push:
    branches:
      - master
#    paths:
#      - 'orc/**'

jobs:
  deploy-serverless:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Serverless Framework
        run: |
          npm install -g serverless@3
#          serverless plugin install -n serverless-python-requirements

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r orc/requirements.txt

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::090268630745:role/github_deploy_role

      - name: Serverless hack
        run: |
          echo Copy serverless.yaml file to the root folder
          cp orc/serverless.yml ./serverless.yml

      - name: Deploy to AWS
        run: |
          . venv/bin/activate
          serverless deploy
